# -*- coding: utf-8 -*-
"""Klasifikasi Jenis Bunga Iris

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7CG_sVQo5BQUfg1lzI6AAj4_rdCsDKk
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

iris = load_iris()
X = iris.data
y = iris.target

sns.pairplot(df, hue='species', palette="Set2", diag_kind="kde")
plt.show()

df = pd.DataFrame(X, columns=iris.feature_names)
df['species'] = y
print("Sample data:\n", df.head())

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Akurasi Model:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

conf_mat = confusion_matrix(y_test, y_pred)
sns.heatmap(conf_mat, annot=True, cmap="Blues", fmt="d",
            xticklabels=iris.target_names, yticklabels=iris.target_names)
plt.xlabel("Prediksi")
plt.ylabel("Aktual")
plt.title("Confusion Matrix")
plt.show()